### ISSUE TITLE
Exporting artifacts to a storage box

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift-ci-jobs#1]
Hi,

ci.centos.org officially provide [publicly accessible folder](http://artifacts.ci.centos.org) to store artifacts of CI builds.  More info [here](https://wiki.centos.org/QaWiki/CI/GettingStarted#head-a46ee49e8818ef9b50225c4e9d429f7a079758d2).

However, we need to publish the artifacts to use the limited storage (recommended 3-4 GB).
There are two approaches as per suggestions:
- Delete some of old artifacts with rsync
- Setup an aging process

**Comment by praveenkumar** [comment]
@budhrg What would be nice to have latest successful job bits synced with artifacts server so we also don't have to worry about deleting old artifact or an aging process. 

We do release stuff on github so latest release bits always available here. Artifacts which synced with centos ci will help user to try out latest iso which potentially would be part of next release.

**Comment by hferentschik** [comment]
> What would be nice to have latest successful job bits synced with artifacts server so we also don't have to worry about deleting old artifact or an aging process.

+1 I'd like to see this working as well

**Comment by bstinsonmhk** [comment]
We can age-out things on artifacts.ci based on whatever criteria you decide. 

Current thinking is: Keep artifacts from the latest 10 "passed" jobs, do not sync any artifacts from "failed" jobs, and continuously delete anything older.

If you folks are ok with that policy we can put that in place for you.

**Comment by budhrg** [comment]
> If you folks are ok with that policy we can put that in place for you.

Yes. Exactly what we require :+1: 

Any changes needed from our side @bstinsonmhk ?

**Comment by bstinsonmhk** [comment]
We should have everything we need. The action is on my side to get the age-out job in place. I'll update here when that's ready.

**Comment by budhrg** [comment]
> We should have everything we need. The action is on my side to get the age-out job in place. I'll update here when that's ready.

Great :+1:  thanks @bstinsonmhk

**Comment by hferentschik** [comment]
@budhrg what's the state on this one?

**Comment by budhrg** [comment]
> what's the state on this one?

@hferentschik , I was waiting for @bstinsonmhk as per his comment above.  
Will try to follow up.

**Comment by budhrg** [comment]
Hi @bstinsonmhk , 

By any luck, you get time to work on it?

**Comment by bstinsonmhk** [comment]
There's a space on artifacts.ci.c.o ready, i'd recommend doing a folder for each jobname and under that do a folder for each jobid containing the actual artifacts:

Example:
├── minishift-b2d-iso
│   ├── 1
│   ├── 2
│   └── 3
└── minishift-centos-iso
    ├── 1
    ├── 2
    └── 3

You can populate those from the $JOBNAME and $BUILD_NUMBER environment variables.

**Comment by hferentschik** [comment]
@bstinsonmhk
>  i'd recommend doing a folder for each jobname and under that do a folder for each jobid containing the actual artifacts

So to fully understand here. The Jenkins build id will keep incrementing and we use it as key. This way we can map an artifact to a build. The setup will automatically keep the latest x builds and when x+1 is published the oldest artifact gets deleted. So at most we have x builds per artifact. Correct?
What's x at the moment, or can we configure that from our side. I don't care so much, just wondering.

@budhrg can you look into this?

**Comment by bstinsonmhk** [comment]
Exactly. 

For the age-out process I have the cronjob set to keep the latest 10 jobs (see this comment: https://github.com/minishift/minishift-ci-jobs/issues/1#issuecomment-274723679)

If you'd like a different number of jobs kept, you'll need to let me know.

**Comment by hferentschik** [comment]
ok, thanks. Sounds good to me

**Comment by budhrg** [comment]
After having discussion with @bstinsonmhk , we come into conclusion that adding it as part of respective project repo `centos_ci.sh` script would be more worthy than changing the `minishift-ci-index.yml` JJB file.

**Comment by bstinsonmhk** [comment]
As part of this process could we look at cleaning out the workspace after each job? Is there a reason to keep a copy of the testdata directories around (for example)?

**Comment by budhrg** [comment]
> As part of this process could we look at cleaning out the workspace after each job? Is there a reason to keep a copy of the testdata directories around (for example)?

@bstinsonmhk I believe this line is making sure of this right ? https://github.com/minishift/minishift-ci-jobs/blob/master/minishift-ci-index.yaml#L9

**Comment by budhrg** [comment]
@bstinsonmhk Also, as per aging out policy [here](https://github.com/minishift/minishift-ci-jobs/issues/1#issuecomment-274723679), there should be max 10 artifacts right?

But looking at this link http://artifacts.ci.centos.org/minishift/minishift/pr/ , we are having more then that.

**Comment by budhrg** [comment]
@bstinsonmhk ping, could you check my above comment?

**Comment by budhrg** [comment]
Closing this issue since all the related issues are closed.
- https://github.com/minishift/minishift/issues/415 (minishift)
- https://github.com/minishift/minishift-centos-iso/issues/101 (minishift-centos-iso)
- https://github.com/minishift/minishift-b2d-iso/issues/27 (minishift-b2d-iso)

Note: The cleanup part of the artifacts are been taken care by CentOS CI team after discussion.
