### ISSUE TITLE
Change the name of build master and pull request jobs

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift-ci-jobs#18]
Right now the Pull request job name is https://ci.centos.org/job/minishift/ and master job name is https://ci.centos.org/job/minishift-build-master.

Update it to https://ci.centos.org/job/minishift/ for master job and
https://ci.centos.org/job/minishift-pr/ for pull request job.

**Comment by budhrg** [comment]
Waiting for ci admin to update service-job configuration to include deleting old jobs other this change will create new jobs and existing jobs will remain there.

**Comment by budhrg** [comment]
@bstinsonmhk Let me know when you are done with required changes from your side.

**Comment by bstinsonmhk** [comment]
Ok, the service job is ready. Can you open a PR with the changes (don't merge yet), and I can coordinate the rename?

**Comment by budhrg** [comment]
Sent the PR @bstinsonmhk  here https://github.com/minishift/minishift-ci-jobs/pull/19
