### ISSUE TITLE
Unable to see complete build logs in nightly builds 

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift-ci-jobs#56]
Hi @bstinsonmhk ,

From last few weeks, we are noticing that our nightly jobs doesn't have complete build logs.
See one https://ci.centos.org/job/minishift-nightly-centos/101/console with the screenshot below.
![screenshot from 2018-03-26 12-17-21](https://user-images.githubusercontent.com/1132451/37890863-b4d1b550-30ef-11e8-87cd-cb827c461b01.png)

Above is the case of successful job where we don't look into logs.

Problem start when we have failed nightly job like https://ci.centos.org/job/minishift-nightly-centos/100/console  where we can't able to see logs

**Comment by budhrg** [comment]
Hi @bstinsonmhk , any opinion here?

**Comment by kbsingh** [comment]
are all your jobs failing like this or only the nightly ones ?

**Comment by budhrg** [comment]
> are all your jobs failing like this or only the nightly ones ?

@kbsingh Nightly ones which run at midnight. However, it is resolved now. Following is the response by Brian on email.

```
We have a cleanup job that runs at midnight and zips up any jenkins logs
it finds (Jenkins can serve gzip'd log files directly in the web UI, so
we do this to save disk space on the master). It looks like this process
was mischecking the modification times on jobs that run concurrently
like your nightly jobs which also run at midnight.

I've updated our process to do a better check on these. You should see
full console from today.
```

**Comment by budhrg** [comment]
Closing as it is resolved now.
