### ISSUE TITLE
Add a skip integration test parameter for release job.

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift-ci-jobs#63]
Sometimes we know the exact reason why the release job is failed so this parameter is used to retrigger the known failure job. This should not be used on the first run for release and also the failure reason should be known and discussed. This is also not going to make any effect on PR or nightly jobs.

- https://ci.centos.org/job/minishift-release/113/console

**Comment by LalatenduMohanty** [comment]
Issue in Minishift repository  https://github.com/minishift/minishift/issues/2850

**Comment by praveenkumar** [comment]
resolved by #74
